### PR TITLE
Add event tags malformed warning

### PR DESCRIPTION
**Pull request by tengattack**
related to https://github.com/tsaikd/gogstash/pull/45

### CODE REVIEW

**Comment by tengattack** [comment]
BTW, the CI seems not start automatically

**Comment by tsaikd** [comment]
https://travis-ci.org/tsaikd/gogstash/builds/429502323
I think travis still work

**Comment by tsaikd** [comment]
GitHub Services are being deprecated, and travis say `open source repositories will be migrated to travis-ci.com gradually. The migration was planned to start at the end of Q2 2018, but has been pushed back.`
I think travis will work now, and I will reconfigure if it break in the future.

**Comment by tengattack** [comment]
I see

**Pull request merged**
