### PR TITLE
Update json encoder/decoder

### PR DESCRIPTION
**Pull request by tengattack**
I try using [jsoniter](https://github.com/json-iterator/go) as the JSON decoder for redis message and encoder for event indexing to elastic, it brings me about 20% performance improvement.

### CODE REVIEW

**Comment by tengattack** [comment]
In fact, I test them as decoder and encoder separately, both of the replacement can make some improvement

**Comment by tengattack** [comment]
made a benchmark here:
```
$ go test -benchmem -run=^$ github.com/tsaikd/gogstash/config/logevent -bench .
goos: windows
goarch: amd64
pkg: github.com/tsaikd/gogstash/config/logevent
Benchmark_JSONEx-16               200000              6521 ns/op          28.21 MB/s        1904 B/op         31 allocs/op
Benchmark_JSONIter-16             500000              2694 ns/op          68.28 MB/s         512 B/op          8 allocs/op
Benchmark_StdJSON-16              200000              6521 ns/op          28.21 MB/s        1904 B/op         31 allocs/op
PASS
ok      github.com/tsaikd/gogstash/config/logevent      4.195s
```

**Comment by tengattack** [comment]
The udp socket test failed because the order of json object keys become uncertain, I'm trying to find a solution.

**Comment by tsaikd** [comment]
when using std compatiable jsonIter, the performance is the same level with std json lib.

```
$ go version
go version go1.11 darwin/amd64
$ go test -v -bench .
...
Benchmark_Marshal_JSONEx-4     	  200000	      7461 ns/op	  24.12 MB/s
Benchmark_Marshal_JSONIter-4   	  200000	      6796 ns/op	  26.48 MB/s
Benchmark_Marshal_StdJSON-4    	  200000	      6926 ns/op	  25.99 MB/s
```

**Comment by tengattack** [comment]
Oh, however in my mechine, it still have ~20% improvement

```
go.exe test -benchmem -run=^$ github.com/tsaikd/gogstash/config/logevent -bench ^Benchmark_Marshal_
goos: windows
goarch: amd64
pkg: github.com/tsaikd/gogstash/config/logevent
Benchmark_Marshal_JSONEx-16               200000              6660 ns/op          27.62 MB/s        1904 B/op         31 allocs/op
Benchmark_Marshal_JSONIter-16             300000              5371 ns/op          34.26 MB/s        2192 B/op         33 allocs/op
Benchmark_Marshal_StdJSON-16              200000              6626 ns/op          27.77 MB/s        1904 B/op         31 allocs/op
PASS
ok      github.com/tsaikd/gogstash/config/logevent      4.541s
```

**Comment by tsaikd** [comment]
go1.11?

**Comment by tengattack** [comment]
Sorry, I'm go1.10, after I upgraded to go1.11:
```
$ go.exe test -benchmem -run=^$ github.com/tsaikd/gogstash/config/logevent -bench ^Benchmark_Marshal_
goos: windows
goarch: amd64
pkg: github.com/tsaikd/gogstash/config/logevent
Benchmark_Marshal_JSONEx-16               200000              6236 ns/op          29.50 MB/s        1904 B/op         31 allocs/op
Benchmark_Marshal_JSONIter-16             300000              5412 ns/op          34.00 MB/s        2191 B/op         33 allocs/op
Benchmark_Marshal_StdJSON-16              300000              5886 ns/op          31.26 MB/s        1456 B/op         29 allocs/op
PASS
ok      github.com/tsaikd/gogstash/config/logevent      5.205s
```

**Comment by tengattack** [comment]
But without std compatible, it still show a great improvement. I will try to modify the socket output test.

**Comment by tengattack** [comment]
```
$ go.exe test -benchmem -run=^$ github.com/tsaikd/gogstash/config/logevent -bench ^Benchmark_Marshal_
goos: windows
goarch: amd64
pkg: github.com/tsaikd/gogstash/config/logevent
Benchmark_Marshal_JSONEx-16               200000              6331 ns/op          29.06 MB/s        1904 B/op         31 allocs/op
Benchmark_Marshal_JSONIter-16             500000              2728 ns/op          67.43 MB/s         512 B/op          8 allocs/op
Benchmark_Marshal_StdJSON-16              200000              5871 ns/op          31.34 MB/s        1456 B/op         29 allocs/op
PASS
ok      github.com/tsaikd/gogstash/config/logevent      4.359s
```

**Comment by tengattack** [comment]
Yep, I remove std compatible, you can fetch the latest code

**Pull request merged**
