### PR TITLE
Elastic legacy

### PR DESCRIPTION
**Pull request by pachico**
This change should allow this plugin to work in new and old Elasticsearch versions. 
What do you think about it?

### CODE REVIEW

**Comment by tsaikd** [comment]
https://github.com/tsaikd/gogstash/tree/0.1.21/output/elasticv5

Add the v5 module back. You can close #130 and #128, If it's solved your problem.

**Comment by pachico** [comment]
Thanks a lot, sir

**Comment by aantono** [comment]
Does this work with Elastic 6.x as well as the 5.x lines?

**Comment by tsaikd** [comment]
I'm not sure, you need to test by yourself for the dedicated features.

**Pull request closed without merging**
