### PR TITLE
Udp packetmode

### PR DESCRIPTION
**Pull request by helgeolav**
A new PR based on all changes in #148.

### CODE REVIEW

**Comment by tsaikd** [comment]
The PR is conflicted now. Please rebase and resolve all conflicts. If you don't know how to do, please follow the commands below.

```sh
# clone to a brand new directory
git clone -b udp2 git@github.com:helgeolav/gogstash.git demo-git-gogstash
cd demo-git-gogstash
# add remote upstream
git remote add upstream git@github.com:tsaikd/gogstash.git
git fetch upstream
# start to rebase
git rebase -i upstream/master
# resolve all conflicts in your favor editor
git add CONFLICTS_FILE
git rebase --continue
# force push the outdated branch to update the PR
git push origin -f udp2
```

**Comment by helgeolav** [comment]
Hi

Thanks for your tips. This part of git I am really having a hard time to understand. This change should not have caused a conflict in the first place, but it seems like I took some old commits with me on this branch, and that caused the issues?

I have tried to resolve these issues now, and I hope that it looks better. If not it is tempting to create a new branch from the current master and a new PR from there.

**Comment by tsaikd** [comment]
The conflict caused by another PR was merged.

You resolved the conflict now, but the commits of PR are still not clean. You have 3 commits in this PR and their descriptions are the same words `UDP packet mode`. I don't think it's necessary to have 3 commits in the case. `git rebase -i` command will give you the chance to reorganize all commits.

**Comment by helgeolav** [comment]
I deleted the branch. I tried many times and many ways and I could not get rid for the commits. I have tried squashing on other repos without issues, so it seems to be something with this fork. The two commits I have issues with seems to be a change that you proposed in one of my first PR that I somehow managed to get into this fork.

**Pull request closed without merging**
